apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-deploy-argoapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/Arog-AppSet.git
    targetRevision: HEAD
    path: apps/overlays/ngix
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
