apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
metadata:
  name: value-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamraj007/Arog-AppSet.git
    targetRevision: value
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
