apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-web-frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-nginx
      name: frontend-mynginx
  template:
    metadata:
      labels:
        app: gitops-nginx
        name: frontend-mynginx
    spec:
      containers:
      - image: iamraj007/my-nginx:backend
        name: frontend-podnginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Namespace
metadata:
  name: frontend
  labels:
    azure-key-vault-env-injection: enabled
